services:
  dockge-agent:
    image: louislam/dockge:1
    container_name: dockge-agent
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ${HOMELAB_DIR}:${HOMELAB_DIR}
    environment:
      - DOCKGE_STACKS_DIR=${HOMELAB_DIR}
