services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - APP_URL=http://192.168.1.100:8082
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=sqlite
    volumes:
      - ./config:/config
